### ISSUE TITLE
Failed to load the dict-en2ja package

### ISSUE THREAD

**Issue by tsuga123** [ta1kt0me/dict-en2ja#7]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.10.5
**Thrown From**: [dict-en2ja](https://github.com/ta1kt0me/dict-en2ja) package, v2.0.1

### Stack Trace

Failed to load the dict-en2ja package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/suganumatakashi/.atom/packages/dict-en2ja/lib/dict-en2ja-view.coffee:1:1)
    at /Users/suganumatakashi/.atom/packages/dict-en2ja/lib/dict-en2ja-view.coffee:5:3
    at Object.<anonymous> (/Users/suganumatakashi/.atom/packages/dict-en2ja/lib/dict-en2ja-view.coffee:5:3)
    at Object.<anonymous> (/Users/suganumatakashi/.atom/packages/dict-en2ja/lib/dict-en2ja-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/suganumatakashi/.atom/packages/dict-en2ja/lib/dict-en2ja.coffee:1:17)
    at Object.<anonymous> (/Users/suganumatakashi/.atom/packages/dict-en2ja/lib/dict-en2ja.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:397:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:743:28
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
dict-en2ja, v2.0.1
japanese-dictionary, v0.2.0
japanese-word-selection, v0.4.0
japanese-wrap, v0.2.7

# Dev
No dev packages
```

**Comment by ta1kt0me** [comment]
Thanks, I've released new fixed version.
